### ISSUE TITLE
No value defined for temporary

### ISSUE THREAD

**Issue by cgay** [dylan-lang/opendylan#1523] opened 2023-07-15 18:43 UTC
Reproducer: https://play.opendylan.org/shared/d085b8e00fe79ab9

```dylan
iterate loop (a = #f, b = 1)
  if (b == 3)
    b
  else
    loop(b, b + 1)
  end
end
```

The above compiles without error if `loop(b, b + 1)` is changed to `loop(a, b + 1)`.

**Comment by housel** [comment] 2023-07-19 14:11
This might be a duplicate of #1461.

**Comment by housel** [comment] 2024-07-01 03:04
Fixed by #1622.

**Closed by housel** 2024-07-01 03:04 UTC
Labels: Compiler
